url: https://niccolospa.github.io

# Site settings
title: "INKY DJ"
email: niccolospa@gmail.com
description: "INKY DJ non ha bisogno di una descrizione perché è magnifico."

# Build settings
markdown: kramdown
permalink: pretty
